export const MONGO_URI = 'mongodb://127.0.0.1:27017/twitter'
export const SESSION_SCERET = 'thisismysecrctekeyfhrgfgrfrty84fwir767'

export const ERROR_MSG = {
    NO_USER_FOUND: 'NO_USER_FOUND',
    USERNAME_NOT_AVAILABLE: 'USERNAME_NOT_AVAILABLE',
    USERNAME_PASSWORD_MISMATCH: 'USERNAME_PASSWORD_MISMATCH',
    NO_TWEET_FOUND: 'NO_TWEET_FOUND',
    TWEET_NOT_CREATED: 'TWEET_NOT_CREATED',
    UPDATE_NOT_ALLOWED: 'UPDATE_NOT_ALLOWED',
    TWEET_NOT_UPDATED: 'TWEET_NOT_UPDATED',
    INVALID_TWEET_ID: 'INVALID_TWEET_ID'
}

